<?php

namespace common;

class SqlConstants {
	
	public static $BLOG_SELECT = "SELECT B.ID, B.TITLE, B.AUTHOR, B.CONTENT, B.CREATE_TIME, B.VIEW_NUM, B.WEIGHT, B.URL, B.CATEGORY_ID, B.LIKES, B.COMMENTS ";
	
	public static $GET_BLOG_BY_CAT_ID = "SELECT B.ID, B.TITLE, B.AUTHOR, B.CONTENT, B.CREATE_TIME, B.VIEW_NUM, B.WEIGHT, B.URL, B.CATEGORY_ID
				  FROM BLOG AS B
                  WHERE B.CATEGORY_ID  = ? ORDER BY B.CREATE_TIME DESC LIMIT ?,?";
	
	public static $GET_BLOG_BY_CAT_ID_COUNT = "SELECT COUNT(1)
				  FROM BLOG AS B
                  WHERE B.CATEGORY_ID  = ? ";
	
	public static $GET_BLOG_BY_ID = "FROM BLOG AS B WHERE B.ID=? ";
	
	public static $INSERT_BLOG = "INSERT INTO BLOG (TITLE, AUTHOR, CONTENT, CREATE_TIME, VIEW_NUM, WEIGHT, URL, CATEGORY_ID) VALUES(?,?,?,now(),?,?,?, ?)";

	public static $QUERY_BLOG = "FROM BLOG AS B ORDER BY B.CREATE_TIME DESC LIMIT ?, ? ";
	
	public static $QUERY_HOT_BLOG = "FROM BLOG AS B ORDER BY B.VIEW_NUM DESC LIMIT ? ";
	
	public static $QUERY_CATEGORY = "SELECT CATEGORY_ID, CATEGORY_NAME, PARENT_ID, WEIGHT, URL, LEVEL FROM CATEGORY WHERE LEVEL = ? ORDER BY WEIGHT DESC";

	public static $UPDATE_BLOG_VIEW_BY_ID = "UPDATE BLOG SET VIEW_NUM =? where id = ?";
	
	public static $GET_ALL_CATEGORY = "SELECT CATEGORY_ID, CATEGORY_NAME, PARENT_ID, WEIGHT, URL, LEVEL FROM CATEGORY WHERE 1 = ? ORDER BY WEIGHT DESC";
	
	public static $QUERY_BLOG_OF_FIRST_CATE = "FROM BLOG AS B WHERE CATEGORY_ID IN(SELECT C.CATEGORY_ID FROM CATEGORY AS C WHERE PARENT_ID = ?) ORDER BY B.WEIGHT DESC, CREATE_TIME DESC LIMIT ?,?";
	
	public static $QUERY_BLOG_OF_FIRST_CATE_COUNT = "SELECT COUNT(1) FROM BLOG AS B WHERE CATEGORY_ID IN(SELECT C.CATEGORY_ID FROM CATEGORY AS C WHERE PARENT_ID = ?)";
	
	public static $QUERY_HOT_BLOGS = "FROM BLOG AS B ORDER BY VIEW_NUM DESC LIMIT ?";
	
	public static $QUERY_NEW_BLOGS = "FROM BLOG AS B ORDER BY B.CREATE_TIME DESC LIMIT ?";
	
	public static $QUERY_PORTAL_BLOGS = "FROM BLOG AS B where B.ID IN (SELECT P.BLOG_ID FROM PORTAL_SHOW AS P WHERE P.AREA_ID = ?) ORDER BY B.CREATE_TIME DESC LIMIT ?";
	
	public static $UPDATE_PORTAL_BLOGS = "
UPDATE PORTAL_SHOW 
SET BLOG_ID = ?, update_time = NOW()
WHERE BLOG_ID =
(
SELECT A.BLOG_ID
FROM 
(
SELECT P.BLOG_ID
FROM PORTAL_SHOW AS P
WHERE AREA_ID = ?
ORDER BY P.update_time ASC
LIMIT 1
) A
)";
	
	
}

?>