<?php

namespace common;

class SqlConstants {
	public static $GET_BLOG_BY_CAT_ID = "SELECT B.ID, B.TITLE, B.AUTHOR, B.CONTENT, B.CREATE_TIME, B.VIEW_NUM, B.WEIGHT, B.URL, B.CATEGORY_ID
				  FROM BLOG AS B
                  WHERE B.CATEGORY_ID  = ? ORDER BY B.WEIGHT ASC LIMIT ?,?";
	
	public static $GET_BLOG_BY_ID = "SELECT B.ID, B.TITLE, B.AUTHOR, B.CONTENT, B.CREATE_TIME, B.VIEW_NUM, B.WEIGHT, B.URL, B.CATEGORY_ID
				  FROM BLOG AS B WHERE B.ID=? ";
	
	public static $INSERT_BLOG = "INSERT INTO BLOG (TITLE, AUTHOR, CONTENT, CREATE_TIME, VIEW_NUM, WEIGHT, CATEGORY_ID) VALUES(?,?,?,now(),?,?,?)";

	public static $QUERY_BLOG = "SELECT B.ID, B.TITLE, B.AUTHOR, B.CONTENT, B.CREATE_TIME, B.VIEW_NUM, B.WEIGHT, B.URL, B.CATEGORY_ID
				  FROM BLOG AS B
                  ORDER BY B.WEIGHT ASC LIMIT ?, ? ";
	
	public static $QUERY_CATEGORY = "SELECT CATEGORY_ID, CATEGORY_NAME, PARENT_ID, WEIGHT, URL, LEVEL FROM CATEGORY WHERE LEVEL = ? ORDER BY WEIGHT DESC";

	public static $UPDATE_BLOG_VIEW_BY_ID = "UPDATE BLOG SET VIEW_NUM =? where id = ?";
	
	
}

?>